@startuml
package modelo{
    class AgloBlocks
    class Algoritmo
    interface Bloque
    class BloqueAbajo
    class BloqueArriba
    class BloqueDerecha
    class BloqueInverso
    class BloqueIterativo
    class BloqueIzquierda
    class BloquePersonalizado
    class BloqueRepetir
    interface Lapiz
    class LapizAbajo
    class LapizArriba
    class Personaje
    class Posicion
    class SectorDibujo
}
@enduml