@startuml
package vista{
    package Botones{
        class BotonAbajoEventHandler
        class BotonArriba
        class BotonBajarLapiz
        class BotonDerecha
        class BotonEjecutar
        class BotoneraMovimientos
        class BotonGuardar
        class BotonInvertir
        class BotonIzquierda
        class BotonReiniciar
        class BotonRepetirDosVeces
        class BotonRepetirTresVeces
        class BotonSubirLapiz
        class IngresarNombre
    }
    package Contenedores{
        class BarraMenu
        class ContenedorAlgoritmo
        class ContenedorCentral
        class ContenedorLapiz
        class ContenedorVertical
        class CreadorSectorTablero
        class FondoVentana
        class InicializadorModelo
        class Scrollable
        class Titulo
    }
    class Dibujador
    class Juego
    class Main
}
@enduml