@startuml

class AlgoBlocks{
    + agregarLista(List<Bloque>)
    + agregarLapizArriba()
    + agregarLapizAbajo()
    + agregarBloqueDerecha()
    + agregarBloqueAbajo()
    + agregarBloqueIzquierda()
    + agregarBloqueArriba()
    + agregarBloqueRepetirDosVeces(): BloqueRepetir
    + agregarBloqueRepetirTresVeces(): BloqueRepetir
    + agregarBloqueInverso(): BloqueInverso
    + guardarAlgoritmo(String)
    + agregarAlgoritmoPersonalizado(String)
    + reiniciar()
}
AlgoBlocks *--- "*" Bloque
AlgoBlocks ....> Lapiz

interface Bloque{
    ejecutar(Personaje)
    opuesto(): Bloque
}

Bloque ...> Personaje

class Personaje{
    + obtenerLapiz(): Lapiz
    + subirLapiiz()
    + actualizarPosicionFinal(Posicion)
    + obtenerPosicion(): Posicion
    + dibujar()
}
Personaje *--- "2"Posicion
Personaje *--- Lapiz

class Algoritmo{
     + Algoritmo(Personaje)
     + ejecutar()
     + agregarLista(AlgoBlocks)
}
Algoritmo *--- "*" Bloque
Algoritmo o--- Personaje
@enduml