@startuml

interface Bloque{
     ejecutar(Personaje)
}

class BloqueDerecha implements Bloque{
}

class BloqueAbajo implements Bloque{
}

class BloqueIzquierda implements Bloque{
}

class BloqueArriba implements Bloque{
}



@enduml