@startuml

interface Lapiz{
    dibujar(int[2])
}
class LapizAbajo implements Lapiz, Bloque{
}
LapizAbajo ...> SectorDibujo

class LapizArriba implements Lapiz, Bloque{
    - List<int[2]>
}

class SectorDibujo{
    - {static} SectorDibujo
    - List<int[2]>
    - SectorDibujo()
    - {static} crearInstancia()
    + {static} obtenerSectorDibujo(): SectorDibujo
    + agregarDibujo(int[2])
    + obtenerDibujo(): int[2]
}


@enduml