@startuml

interface Recorrido{
     ejecutar()
     agregarBloque(): AlgoBlocks
     obtenerRecorrido(): List<Bloque>
 }

 class RecorridoInverso implements Recorrido{
     - List<Bloque>
     - Personaje
     + RecorridoInverso(Personaje)
 }

 class RecorridoIterativo implements Recorrido{
     - List<Bloque>
     - int
     - Personaje
     + RecorridoIterativo(int, Personaje)
 }

 class RecorridoSinRepeticion implements Recorrido{
     - List <Bloque>
     - Personaje
     + RecorridoSinRepeticion(Personaje)
 }

@enduml