@startuml

class SectorDibujo{
    - {static} SectorDibujo
    - List<int[2]>
    - SectorDibujo()
    - {static} crearInstancia()
    + {static} obtenerSectorDibujo(): SectorDibujo
    + agregarDibujo(int[2])
    + obtenerDibujo(): int[2]
}

@enduml