@startuml

header page header
title test05MoverIzquierdaConBloqueMoverIzquierdaPersonajeSeMueveIzquierda
actor test05

test05 -> AlgoBlocks: agregarBloqueIzquierda()
create BloqueIzquierda
AlgoBlocks -> BloqueIzquierda: new BloqueIzquierda()
BloqueIzquierda --> AlgoBlocks: algoritmo.add(BloqueIzquierda)
test05 -> AlgoBlocks: ejecutar()
AlgoBlocks -> BloqueIzquierda: ejecutar(personaje)
BloqueIzquierda -> Personaje: actualizarPosicion(-1, 0)
Personaje --> Personaje: posicion = (-1, 0)
BloqueIzquierda -> Personaje: dibujar()
Personaje -> LapizAbajo: dibujar(-1 ,0)
create SectorDibujo
LapizAbajo -> SectorDibujo: agregarADibujo(posiciion)
SectorDibujo --> SectorDibujo: dibujo.add(posiciion)
@enduml