@startuml

header page header
title test13UsarBloqueRepetirTresVecesYPersonajeSeMueveCorrectamente
actor Test13

Test13 -> AlgoBlocks: agregarBloqueDerecha()
create Bloque
AlgoBlocks -> Bloque: new Bloque()
Bloque --> AlgoBlocks: algoritmo.add(Bloque)
Test13 -> AlgoBlocks: agregarBloqueArriba()
create Bloque
AlgoBlocks -> Bloque: new Bloque()
Bloque --> AlgoBlocks: algoritmo.add(Bloque)
Test13 -> AlgoBlocks: agregarBloqueRepetirTresVeces()
create BloqueRepetir
AlgoBlocks -> BloqueRepetir: new BloqueRepetir(3, personaje)
BloqueRepetir --> BloqueRepetir: repetir = 3\npersonaje = Personaje
BloqueRepetir --> AlgoBlocks: algoritmo.add(BloqueRepetir)
AlgoBlocks --> Test13: bloqueRepetir = BloqueRepetir
Test13 -> BloqueRepetir: agregarBloque()
BloqueRepetir -> AlgoBlocks: new AlgoBlocks(algoritmo, personaje)
BloqueRepetir --> Test13: algoritmoIterativo = AlgoBlocks
Test13 -> AlgoBlocks: agregarBloqueDerecha()
create Bloque
AlgoBlocks -> Bloque: new Bloque()
Bloque --> AlgoBlocks: algoritmo.add(Bloque)
Test13 -> AlgoBlocks: agregarBloqueAbajo()
create Bloque
AlgoBlocks -> Bloque: new Bloque()
Bloque --> AlgoBlocks: algoritmo.add(Bloque)
Test13 -> AlgoBlocks: ejecutar()
loop algoritmo.size()
    AlgoBlocks -> Bloque: ejecutar()
    AlgoBlocks -> BloqueRepetir: ejecutar()
    loop BloqueRepetir.repeticion
        BloqueRepetir -> BloqueRepetir: recorrer(personaje)
        loop BloqueIterativo.algoritmo.size()
            AlgoBlocks -> Bloque: ejecutar(personaje)
        end
    end
end

@enduml