@startuml
header page header
title Creacion de Personaje, Algoritmo y AlgoBlocks
actor Usuario

create Personaje
Usuario -> Personaje: new Personaje()
create Posicion
Personaje -> Posicion: new Posicion(0, 0)
Posicion --> Personaje: posicionInicial =  Posicion\nposicionFinal = Posicion
create LapizArriba
Personaje -> LapizArriba: new LapizArriba()
LapizArriba --> Personaje: lapiz = LapizArriba
Personaje --> Usuario: personaje = Personaje
create Algoritmo
Usuario -> Algoritmo: new Algoritmo(personaje)
Algoritmo -> Algoritmo: personaje = Personaje
create AlgoBlocks
Usuario -> AlgoBlocks: new AlgoBlocks()
AlgoBlocks --> Usuario: algoBlocks =  AlgoBlocks
Usuario -> Algoritmo: agregarLista(algoBlocks)

@enduml